// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Record struct {
	ID         int64
	UserName   string
	RecordName string
	DataType   string
	Payload    []byte
	Nonce      []byte
	SyncStatus string
	CreatedAt  string
	UpdatedAt  string
}

type User struct {
	ID           sql.NullInt64
	UserName     string
	PasswordHash string
}
