// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
)

const deleteRecord = `-- name: DeleteRecord :exec
= ?
ORDER BY created_at DESC;

DELETE FROM records
WHERE use
`

type DeleteRecordParams struct {
	UserName   string
	RecordName string
}

func (q *Queries) DeleteRecord(ctx context.Context, arg DeleteRecordParams) error {
	_, err := q.db.ExecContext(ctx, deleteRecord, arg.UserName, arg.RecordName)
	return err
}

const getAllRecordsByUsername = `-- name: GetAllRecordsByUsername :many
_name = ? AND record_name = ?;

SELECT id, user_name, record_name, data_type, payload, nonce, sync_status, created_at, updated_at
FROM records
WHERE user_nam
`

func (q *Queries) GetAllRecordsByUsername(ctx context.Context, userName string) ([]Record, error) {
	rows, err := q.db.QueryContext(ctx, getAllRecordsByUsername, userName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Record
	for rows.Next() {
		var i Record
		if err := rows.Scan(
			&i.ID,
			&i.UserName,
			&i.RecordName,
			&i.DataType,
			&i.Payload,
			&i.Nonce,
			&i.SyncStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingRecords = `-- name: GetPendingRecords :many
_name = ? AND record_name = ?;


SELECT id, user_name, record_name, data_type, payload, nonce, cre
`

type GetPendingRecordsRow struct {
	ID         int64
	UserName   string
	RecordName string
	DataType   string
	Payload    []byte
	Nonce      []byte
	CreatedAt  string
	UpdatedAt  string
}

// ============================================================================
// СЛУЖЕБНЫЕ ЗАПРОСЫ ДЛЯ СИНХРОНИЗАЦИИ
// ============================================================================
func (q *Queries) GetPendingRecords(ctx context.Context) ([]GetPendingRecordsRow, error) {
	rows, err := q.db.QueryContext(ctx, getPendingRecords)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPendingRecordsRow
	for rows.Next() {
		var i GetPendingRecordsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserName,
			&i.RecordName,
			&i.DataType,
			&i.Payload,
			&i.Nonce,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecordByUniqueKey = `-- name: GetRecordByUniqueKey :one
tatus, created_at, updated_at;

SELECT id, user_name, record_name, data_type, payload, nonce, sync_status, created_at, updated_at
FROM records
WHERE use
`

type GetRecordByUniqueKeyParams struct {
	UserName   string
	RecordName string
}

func (q *Queries) GetRecordByUniqueKey(ctx context.Context, arg GetRecordByUniqueKeyParams) (Record, error) {
	row := q.db.QueryRowContext(ctx, getRecordByUniqueKey, arg.UserName, arg.RecordName)
	var i Record
	err := row.Scan(
		&i.ID,
		&i.UserName,
		&i.RecordName,
		&i.DataType,
		&i.Payload,
		&i.Nonce,
		&i.SyncStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const saveRecord = `-- name: SaveRecord :one

INSERT INTO records (user_name, record_name, data_type, payload, nonce, sync_status, updated_at)
VALUES (?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)
ON CONFLICT(user_name, record_name) DO UPDATE SET
    data_type = excluded.data_type,
    payload = excluded.payload,
    nonce = excluded.nonce,
    sync_status = excluded.sync_status,
    updated_at = CURRENT_TIMESTAMP
RETURNING id, user_name, record_name, data_type, payload, nonce, sync_
`

type SaveRecordParams struct {
	UserName   string
	RecordName string
	DataType   string
	Payload    []byte
	Nonce      []byte
	SyncStatus string
}

// ============================================================================
// ЗАПРОСЫ ДЛЯ ТАБЛИЦЫ RECORDS (КЛИЕНТСКИЙ КЭШ)
// ============================================================================
func (q *Queries) SaveRecord(ctx context.Context, arg SaveRecordParams) (Record, error) {
	row := q.db.QueryRowContext(ctx, saveRecord,
		arg.UserName,
		arg.RecordName,
		arg.DataType,
		arg.Payload,
		arg.Nonce,
		arg.SyncStatus,
	)
	var i Record
	err := row.Scan(
		&i.ID,
		&i.UserName,
		&i.RecordName,
		&i.DataType,
		&i.Payload,
		&i.Nonce,
		&i.SyncStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSyncStatus = `-- name: UpdateSyncStatus :exec
ted_at, updated_at
FROM records
WHERE sync_status = 'pending';

`

// Переводит запись в статус 'synced' по
func (q *Queries) UpdateSyncStatus(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, updateSyncStatus, id)
	return err
}
