services:
  db:
    image: postgres:16-alpine
    container_name: goph_keeper
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432"