// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Record struct {
	ID         int32
	UserName   string
	RecordName string
	DataType   string
	Payload    []byte
	Nonce      []byte
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type User struct {
	ID           pgtype.Int4
	UserName     string
	PasswordHash string
}
