// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
)

const createRecord = `-- name: CreateRecord :one

INSERT INTO records (user_name, record_name, data_type, payload, nonce)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_name, record_name, data_type, payload, nonce, created_at, updated_at
`

type CreateRecordParams struct {
	UserName   string
	RecordName string
	DataType   string
	Payload    []byte
	Nonce      []byte
}

// ============================================================================
// ЗАПРОСЫ ДЛЯ ТАБЛИЦЫ RECORDS
// ============================================================================
func (q *Queries) CreateRecord(ctx context.Context, arg CreateRecordParams) (Record, error) {
	row := q.db.QueryRow(ctx, createRecord,
		arg.UserName,
		arg.RecordName,
		arg.DataType,
		arg.Payload,
		arg.Nonce,
	)
	var i Record
	err := row.Scan(
		&i.ID,
		&i.UserName,
		&i.RecordName,
		&i.DataType,
		&i.Payload,
		&i.Nonce,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one

INSERT INTO users (user_name, password_hash)
VALUES ($1, $2)
RETURNING user_name, password_hash
`

type CreateUserParams struct {
	UserName     string
	PasswordHash string
}

type CreateUserRow struct {
	UserName     string
	PasswordHash string
}

// ============================================================================
// ЗАПРОСЫ ДЛЯ ТАБЛИЦЫ USERS
// ============================================================================
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.UserName, arg.PasswordHash)
	var i CreateUserRow
	err := row.Scan(&i.UserName, &i.PasswordHash)
	return i, err
}

const deleteRecord = `-- name: DeleteRecord :exec
DELETE FROM records
WHERE user_name = $1 AND record_name = $2
`

type DeleteRecordParams struct {
	UserName   string
	RecordName string
}

func (q *Queries) DeleteRecord(ctx context.Context, arg DeleteRecordParams) error {
	_, err := q.db.Exec(ctx, deleteRecord, arg.UserName, arg.RecordName)
	return err
}

const getAllRecordsByUsername = `-- name: GetAllRecordsByUsername :many
SELECT id, user_name, record_name, data_type, payload, nonce, created_at, updated_at
FROM records
WHERE user_name = $1
ORDER BY created_at DESC
`

func (q *Queries) GetAllRecordsByUsername(ctx context.Context, userName string) ([]Record, error) {
	rows, err := q.db.Query(ctx, getAllRecordsByUsername, userName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Record
	for rows.Next() {
		var i Record
		if err := rows.Scan(
			&i.ID,
			&i.UserName,
			&i.RecordName,
			&i.DataType,
			&i.Payload,
			&i.Nonce,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecordByUniqueKey = `-- name: GetRecordByUniqueKey :one
SELECT id, user_name, record_name, data_type, payload, nonce, created_at, updated_at
FROM records
WHERE user_name = $1 AND record_name = $2
`

type GetRecordByUniqueKeyParams struct {
	UserName   string
	RecordName string
}

func (q *Queries) GetRecordByUniqueKey(ctx context.Context, arg GetRecordByUniqueKeyParams) (Record, error) {
	row := q.db.QueryRow(ctx, getRecordByUniqueKey, arg.UserName, arg.RecordName)
	var i Record
	err := row.Scan(
		&i.ID,
		&i.UserName,
		&i.RecordName,
		&i.DataType,
		&i.Payload,
		&i.Nonce,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT user_name, password_hash
FROM users
WHERE user_name = $1
`

type GetUserByUsernameRow struct {
	UserName     string
	PasswordHash string
}

func (q *Queries) GetUserByUsername(ctx context.Context, userName string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, userName)
	var i GetUserByUsernameRow
	err := row.Scan(&i.UserName, &i.PasswordHash)
	return i, err
}

const updateRecordData = `-- name: UpdateRecordData :one
UPDATE records
SET data_type = $3,
    payload = $4,
    nonce = $5,
    updated_at = NOW()
WHERE user_name = $1 AND record_name = $2
RETURNING id, user_name, record_name, data_type, payload, nonce, created_at, updated_at
`

type UpdateRecordDataParams struct {
	UserName   string
	RecordName string
	DataType   string
	Payload    []byte
	Nonce      []byte
}

func (q *Queries) UpdateRecordData(ctx context.Context, arg UpdateRecordDataParams) (Record, error) {
	row := q.db.QueryRow(ctx, updateRecordData,
		arg.UserName,
		arg.RecordName,
		arg.DataType,
		arg.Payload,
		arg.Nonce,
	)
	var i Record
	err := row.Scan(
		&i.ID,
		&i.UserName,
		&i.RecordName,
		&i.DataType,
		&i.Payload,
		&i.Nonce,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
