// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: gophkeeper.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Модель для текстовых данных
type TextData struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name string                 `protobuf:"bytes,1,opt,name=name,proto3"`
	xxx_hidden_Text string                 `protobuf:"bytes,2,opt,name=text,proto3"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TextData) Reset() {
	*x = TextData{}
	mi := &file_gophkeeper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextData) ProtoMessage() {}

func (x *TextData) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TextData) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *TextData) GetText() string {
	if x != nil {
		return x.xxx_hidden_Text
	}
	return ""
}

func (x *TextData) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *TextData) SetText(v string) {
	x.xxx_hidden_Text = v
}

type TextData_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name string
	Text string
}

func (b0 TextData_builder) Build() *TextData {
	m0 := &TextData{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_Text = b.Text
	return m0
}

// Модель для бинарных данных (файлов)
type BinaryData struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name     string                 `protobuf:"bytes,1,opt,name=name,proto3"`
	xxx_hidden_FileName string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3"`
	xxx_hidden_Data     []byte                 `protobuf:"bytes,3,opt,name=data,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *BinaryData) Reset() {
	*x = BinaryData{}
	mi := &file_gophkeeper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BinaryData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BinaryData) ProtoMessage() {}

func (x *BinaryData) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *BinaryData) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *BinaryData) GetFileName() string {
	if x != nil {
		return x.xxx_hidden_FileName
	}
	return ""
}

func (x *BinaryData) GetData() []byte {
	if x != nil {
		return x.xxx_hidden_Data
	}
	return nil
}

func (x *BinaryData) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *BinaryData) SetFileName(v string) {
	x.xxx_hidden_FileName = v
}

func (x *BinaryData) SetData(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Data = v
}

type BinaryData_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name     string
	FileName string
	Data     []byte
}

func (b0 BinaryData_builder) Build() *BinaryData {
	m0 := &BinaryData{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_FileName = b.FileName
	x.xxx_hidden_Data = b.Data
	return m0
}

// Модель для банковских карт
type CardData struct {
	state                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name           string                 `protobuf:"bytes,1,opt,name=name,proto3"`
	xxx_hidden_CardNumber     string                 `protobuf:"bytes,2,opt,name=card_number,json=cardNumber,proto3"`
	xxx_hidden_ExpirationDate string                 `protobuf:"bytes,3,opt,name=expiration_date,json=expirationDate,proto3"`
	xxx_hidden_Cvv            string                 `protobuf:"bytes,4,opt,name=cvv,proto3"`
	xxx_hidden_CardholderName string                 `protobuf:"bytes,5,opt,name=cardholder_name,json=cardholderName,proto3"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *CardData) Reset() {
	*x = CardData{}
	mi := &file_gophkeeper_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardData) ProtoMessage() {}

func (x *CardData) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CardData) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *CardData) GetCardNumber() string {
	if x != nil {
		return x.xxx_hidden_CardNumber
	}
	return ""
}

func (x *CardData) GetExpirationDate() string {
	if x != nil {
		return x.xxx_hidden_ExpirationDate
	}
	return ""
}

func (x *CardData) GetCvv() string {
	if x != nil {
		return x.xxx_hidden_Cvv
	}
	return ""
}

func (x *CardData) GetCardholderName() string {
	if x != nil {
		return x.xxx_hidden_CardholderName
	}
	return ""
}

func (x *CardData) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *CardData) SetCardNumber(v string) {
	x.xxx_hidden_CardNumber = v
}

func (x *CardData) SetExpirationDate(v string) {
	x.xxx_hidden_ExpirationDate = v
}

func (x *CardData) SetCvv(v string) {
	x.xxx_hidden_Cvv = v
}

func (x *CardData) SetCardholderName(v string) {
	x.xxx_hidden_CardholderName = v
}

type CardData_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name           string
	CardNumber     string
	ExpirationDate string
	Cvv            string
	CardholderName string
}

func (b0 CardData_builder) Build() *CardData {
	m0 := &CardData{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_CardNumber = b.CardNumber
	x.xxx_hidden_ExpirationDate = b.ExpirationDate
	x.xxx_hidden_Cvv = b.Cvv
	x.xxx_hidden_CardholderName = b.CardholderName
	return m0
}

// Универсальный пустой ответ для успешного выполнения
type SaveResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveResponse) Reset() {
	*x = SaveResponse{}
	mi := &file_gophkeeper_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveResponse) ProtoMessage() {}

func (x *SaveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type SaveResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 SaveResponse_builder) Build() *SaveResponse {
	m0 := &SaveResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

var File_gophkeeper_proto protoreflect.FileDescriptor

const file_gophkeeper_proto_rawDesc = "" +
	"\n" +
	"\x10gophkeeper.proto\x12\ttransport\"2\n" +
	"\bTextData\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"Q\n" +
	"\n" +
	"BinaryData\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"\xa3\x01\n" +
	"\bCardData\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vcard_number\x18\x02 \x01(\tR\n" +
	"cardNumber\x12'\n" +
	"\x0fexpiration_date\x18\x03 \x01(\tR\x0eexpirationDate\x12\x10\n" +
	"\x03cvv\x18\x04 \x01(\tR\x03cvv\x12'\n" +
	"\x0fcardholder_name\x18\x05 \x01(\tR\x0ecardholderName\"\x0e\n" +
	"\fSaveResponse2\xc2\x01\n" +
	"\x10TransportService\x128\n" +
	"\bSaveText\x12\x13.transport.TextData\x1a\x17.transport.SaveResponse\x128\n" +
	"\bSaveCard\x12\x13.transport.CardData\x1a\x17.transport.SaveResponse\x12:\n" +
	"\bSaveFile\x12\x15.transport.BinaryData\x1a\x17.transport.SaveResponseB\x14Z\x12internal/shared/pbb\x06proto3"

var file_gophkeeper_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_gophkeeper_proto_goTypes = []any{
	(*TextData)(nil),     // 0: transport.TextData
	(*BinaryData)(nil),   // 1: transport.BinaryData
	(*CardData)(nil),     // 2: transport.CardData
	(*SaveResponse)(nil), // 3: transport.SaveResponse
}
var file_gophkeeper_proto_depIdxs = []int32{
	0, // 0: transport.TransportService.SaveText:input_type -> transport.TextData
	2, // 1: transport.TransportService.SaveCard:input_type -> transport.CardData
	1, // 2: transport.TransportService.SaveFile:input_type -> transport.BinaryData
	3, // 3: transport.TransportService.SaveText:output_type -> transport.SaveResponse
	3, // 4: transport.TransportService.SaveCard:output_type -> transport.SaveResponse
	3, // 5: transport.TransportService.SaveFile:output_type -> transport.SaveResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gophkeeper_proto_init() }
func file_gophkeeper_proto_init() {
	if File_gophkeeper_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gophkeeper_proto_rawDesc), len(file_gophkeeper_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gophkeeper_proto_goTypes,
		DependencyIndexes: file_gophkeeper_proto_depIdxs,
		MessageInfos:      file_gophkeeper_proto_msgTypes,
	}.Build()
	File_gophkeeper_proto = out.File
	file_gophkeeper_proto_goTypes = nil
	file_gophkeeper_proto_depIdxs = nil
}
