// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: gophkeeper.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthRequest struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Username     string                 `protobuf:"bytes,1,opt,name=username,proto3"`
	xxx_hidden_PasswordHash string                 `protobuf:"bytes,2,opt,name=password_hash,json=passwordHash,proto3"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *AuthRequest) Reset() {
	*x = AuthRequest{}
	mi := &file_gophkeeper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRequest) ProtoMessage() {}

func (x *AuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AuthRequest) GetUsername() string {
	if x != nil {
		return x.xxx_hidden_Username
	}
	return ""
}

func (x *AuthRequest) GetPasswordHash() string {
	if x != nil {
		return x.xxx_hidden_PasswordHash
	}
	return ""
}

func (x *AuthRequest) SetUsername(v string) {
	x.xxx_hidden_Username = v
}

func (x *AuthRequest) SetPasswordHash(v string) {
	x.xxx_hidden_PasswordHash = v
}

type AuthRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Username     string
	PasswordHash string
}

func (b0 AuthRequest_builder) Build() *AuthRequest {
	m0 := &AuthRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Username = b.Username
	x.xxx_hidden_PasswordHash = b.PasswordHash
	return m0
}

type AuthResponse struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Token string                 `protobuf:"bytes,1,opt,name=token,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	mi := &file_gophkeeper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AuthResponse) GetToken() string {
	if x != nil {
		return x.xxx_hidden_Token
	}
	return ""
}

func (x *AuthResponse) SetToken(v string) {
	x.xxx_hidden_Token = v
}

type AuthResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Token string
}

func (b0 AuthResponse_builder) Build() *AuthResponse {
	m0 := &AuthResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Token = b.Token
	return m0
}

type ListRecordsRequest struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Limit int32                  `protobuf:"varint,1,opt,name=limit,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ListRecordsRequest) Reset() {
	*x = ListRecordsRequest{}
	mi := &file_gophkeeper_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRecordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecordsRequest) ProtoMessage() {}

func (x *ListRecordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListRecordsRequest) GetLimit() int32 {
	if x != nil {
		return x.xxx_hidden_Limit
	}
	return 0
}

func (x *ListRecordsRequest) SetLimit(v int32) {
	x.xxx_hidden_Limit = v
}

type ListRecordsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Limit int32
}

func (b0 ListRecordsRequest_builder) Build() *ListRecordsRequest {
	m0 := &ListRecordsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Limit = b.Limit
	return m0
}

type ListRecordsResponse struct {
	state              protoimpl.MessageState             `protogen:"opaque.v1"`
	xxx_hidden_Records *[]*ListRecordsResponse_RecordMeta `protobuf:"bytes,1,rep,name=records,proto3"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ListRecordsResponse) Reset() {
	*x = ListRecordsResponse{}
	mi := &file_gophkeeper_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRecordsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecordsResponse) ProtoMessage() {}

func (x *ListRecordsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListRecordsResponse) GetRecords() []*ListRecordsResponse_RecordMeta {
	if x != nil {
		if x.xxx_hidden_Records != nil {
			return *x.xxx_hidden_Records
		}
	}
	return nil
}

func (x *ListRecordsResponse) SetRecords(v []*ListRecordsResponse_RecordMeta) {
	x.xxx_hidden_Records = &v
}

type ListRecordsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Records []*ListRecordsResponse_RecordMeta
}

func (b0 ListRecordsResponse_builder) Build() *ListRecordsResponse {
	m0 := &ListRecordsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Records = &b.Records
	return m0
}

type Record struct {
	state                 protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name       string                 `protobuf:"bytes,1,opt,name=name,proto3"`
	xxx_hidden_DataType   string                 `protobuf:"bytes,2,opt,name=data_type,json=dataType,proto3"`
	xxx_hidden_SecureData []byte                 `protobuf:"bytes,3,opt,name=secure_data,json=secureData,proto3"`
	xxx_hidden_Nonce      []byte                 `protobuf:"bytes,4,opt,name=nonce,proto3"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_gophkeeper_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Record) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *Record) GetDataType() string {
	if x != nil {
		return x.xxx_hidden_DataType
	}
	return ""
}

func (x *Record) GetSecureData() []byte {
	if x != nil {
		return x.xxx_hidden_SecureData
	}
	return nil
}

func (x *Record) GetNonce() []byte {
	if x != nil {
		return x.xxx_hidden_Nonce
	}
	return nil
}

func (x *Record) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *Record) SetDataType(v string) {
	x.xxx_hidden_DataType = v
}

func (x *Record) SetSecureData(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_SecureData = v
}

func (x *Record) SetNonce(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Nonce = v
}

type Record_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name       string
	DataType   string
	SecureData []byte
	Nonce      []byte
}

func (b0 Record_builder) Build() *Record {
	m0 := &Record{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_DataType = b.DataType
	x.xxx_hidden_SecureData = b.SecureData
	x.xxx_hidden_Nonce = b.Nonce
	return m0
}

type GetRecordRequest struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name string                 `protobuf:"bytes,1,opt,name=name,proto3"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetRecordRequest) Reset() {
	*x = GetRecordRequest{}
	mi := &file_gophkeeper_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecordRequest) ProtoMessage() {}

func (x *GetRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetRecordRequest) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *GetRecordRequest) SetName(v string) {
	x.xxx_hidden_Name = v
}

type GetRecordRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name string
}

func (b0 GetRecordRequest_builder) Build() *GetRecordRequest {
	m0 := &GetRecordRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Name = b.Name
	return m0
}

type SaveResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveResponse) Reset() {
	*x = SaveResponse{}
	mi := &file_gophkeeper_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveResponse) ProtoMessage() {}

func (x *SaveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type SaveResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 SaveResponse_builder) Build() *SaveResponse {
	m0 := &SaveResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

// Компактное описание записи для списка
type ListRecordsResponse_RecordMeta struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name     string                 `protobuf:"bytes,1,opt,name=name,proto3"`
	xxx_hidden_DataType string                 `protobuf:"bytes,2,opt,name=data_type,json=dataType,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ListRecordsResponse_RecordMeta) Reset() {
	*x = ListRecordsResponse_RecordMeta{}
	mi := &file_gophkeeper_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRecordsResponse_RecordMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecordsResponse_RecordMeta) ProtoMessage() {}

func (x *ListRecordsResponse_RecordMeta) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListRecordsResponse_RecordMeta) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *ListRecordsResponse_RecordMeta) GetDataType() string {
	if x != nil {
		return x.xxx_hidden_DataType
	}
	return ""
}

func (x *ListRecordsResponse_RecordMeta) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *ListRecordsResponse_RecordMeta) SetDataType(v string) {
	x.xxx_hidden_DataType = v
}

type ListRecordsResponse_RecordMeta_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name     string
	DataType string
}

func (b0 ListRecordsResponse_RecordMeta_builder) Build() *ListRecordsResponse_RecordMeta {
	m0 := &ListRecordsResponse_RecordMeta{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_DataType = b.DataType
	return m0
}

var File_gophkeeper_proto protoreflect.FileDescriptor

const file_gophkeeper_proto_rawDesc = "" +
	"\n" +
	"\x10gophkeeper.proto\x12\ttransport\"N\n" +
	"\vAuthRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12#\n" +
	"\rpassword_hash\x18\x02 \x01(\tR\fpasswordHash\"$\n" +
	"\fAuthResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"*\n" +
	"\x12ListRecordsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"\x99\x01\n" +
	"\x13ListRecordsResponse\x12C\n" +
	"\arecords\x18\x01 \x03(\v2).transport.ListRecordsResponse.RecordMetaR\arecords\x1a=\n" +
	"\n" +
	"RecordMeta\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tdata_type\x18\x02 \x01(\tR\bdataType\"p\n" +
	"\x06Record\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tdata_type\x18\x02 \x01(\tR\bdataType\x12\x1f\n" +
	"\vsecure_data\x18\x03 \x01(\fR\n" +
	"secureData\x12\x14\n" +
	"\x05nonce\x18\x04 \x01(\fR\x05nonce\"&\n" +
	"\x10GetRecordRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x0e\n" +
	"\fSaveResponse2\x94\x03\n" +
	"\x10TransportService\x12;\n" +
	"\bRegister\x12\x16.transport.AuthRequest\x1a\x17.transport.AuthResponse\x128\n" +
	"\x05Login\x12\x16.transport.AuthRequest\x1a\x17.transport.AuthResponse\x128\n" +
	"\n" +
	"SaveRecord\x12\x11.transport.Record\x1a\x17.transport.SaveResponse\x12;\n" +
	"\tGetRecord\x12\x1b.transport.GetRecordRequest\x1a\x11.transport.Record\x12D\n" +
	"\fDeleteRecord\x12\x1b.transport.GetRecordRequest\x1a\x17.transport.SaveResponse\x12L\n" +
	"\vListRecords\x12\x1d.transport.ListRecordsRequest\x1a\x1e.transport.ListRecordsResponseB\aZ\x05./;pbb\x06proto3"

var file_gophkeeper_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_gophkeeper_proto_goTypes = []any{
	(*AuthRequest)(nil),                    // 0: transport.AuthRequest
	(*AuthResponse)(nil),                   // 1: transport.AuthResponse
	(*ListRecordsRequest)(nil),             // 2: transport.ListRecordsRequest
	(*ListRecordsResponse)(nil),            // 3: transport.ListRecordsResponse
	(*Record)(nil),                         // 4: transport.Record
	(*GetRecordRequest)(nil),               // 5: transport.GetRecordRequest
	(*SaveResponse)(nil),                   // 6: transport.SaveResponse
	(*ListRecordsResponse_RecordMeta)(nil), // 7: transport.ListRecordsResponse.RecordMeta
}
var file_gophkeeper_proto_depIdxs = []int32{
	7, // 0: transport.ListRecordsResponse.records:type_name -> transport.ListRecordsResponse.RecordMeta
	0, // 1: transport.TransportService.Register:input_type -> transport.AuthRequest
	0, // 2: transport.TransportService.Login:input_type -> transport.AuthRequest
	4, // 3: transport.TransportService.SaveRecord:input_type -> transport.Record
	5, // 4: transport.TransportService.GetRecord:input_type -> transport.GetRecordRequest
	5, // 5: transport.TransportService.DeleteRecord:input_type -> transport.GetRecordRequest
	2, // 6: transport.TransportService.ListRecords:input_type -> transport.ListRecordsRequest
	1, // 7: transport.TransportService.Register:output_type -> transport.AuthResponse
	1, // 8: transport.TransportService.Login:output_type -> transport.AuthResponse
	6, // 9: transport.TransportService.SaveRecord:output_type -> transport.SaveResponse
	4, // 10: transport.TransportService.GetRecord:output_type -> transport.Record
	6, // 11: transport.TransportService.DeleteRecord:output_type -> transport.SaveResponse
	3, // 12: transport.TransportService.ListRecords:output_type -> transport.ListRecordsResponse
	7, // [7:13] is the sub-list for method output_type
	1, // [1:7] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_gophkeeper_proto_init() }
func file_gophkeeper_proto_init() {
	if File_gophkeeper_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gophkeeper_proto_rawDesc), len(file_gophkeeper_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gophkeeper_proto_goTypes,
		DependencyIndexes: file_gophkeeper_proto_depIdxs,
		MessageInfos:      file_gophkeeper_proto_msgTypes,
	}.Build()
	File_gophkeeper_proto = out.File
	file_gophkeeper_proto_goTypes = nil
	file_gophkeeper_proto_depIdxs = nil
}
