// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: gophkeeper.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Record struct {
	state                 protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name       string                 `protobuf:"bytes,1,opt,name=name,proto3"`
	xxx_hidden_DataType   string                 `protobuf:"bytes,2,opt,name=data_type,json=dataType,proto3"`
	xxx_hidden_SecureData []byte                 `protobuf:"bytes,3,opt,name=secure_data,json=secureData,proto3"`
	xxx_hidden_Nonce      []byte                 `protobuf:"bytes,4,opt,name=nonce,proto3"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_gophkeeper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Record) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *Record) GetDataType() string {
	if x != nil {
		return x.xxx_hidden_DataType
	}
	return ""
}

func (x *Record) GetSecureData() []byte {
	if x != nil {
		return x.xxx_hidden_SecureData
	}
	return nil
}

func (x *Record) GetNonce() []byte {
	if x != nil {
		return x.xxx_hidden_Nonce
	}
	return nil
}

func (x *Record) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *Record) SetDataType(v string) {
	x.xxx_hidden_DataType = v
}

func (x *Record) SetSecureData(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_SecureData = v
}

func (x *Record) SetNonce(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Nonce = v
}

type Record_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name       string
	DataType   string
	SecureData []byte
	Nonce      []byte
}

func (b0 Record_builder) Build() *Record {
	m0 := &Record{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_DataType = b.DataType
	x.xxx_hidden_SecureData = b.SecureData
	x.xxx_hidden_Nonce = b.Nonce
	return m0
}

type GetRecordRequest struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name string                 `protobuf:"bytes,1,opt,name=name,proto3"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetRecordRequest) Reset() {
	*x = GetRecordRequest{}
	mi := &file_gophkeeper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecordRequest) ProtoMessage() {}

func (x *GetRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetRecordRequest) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *GetRecordRequest) SetName(v string) {
	x.xxx_hidden_Name = v
}

type GetRecordRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name string
}

func (b0 GetRecordRequest_builder) Build() *GetRecordRequest {
	m0 := &GetRecordRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Name = b.Name
	return m0
}

type SaveResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveResponse) Reset() {
	*x = SaveResponse{}
	mi := &file_gophkeeper_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveResponse) ProtoMessage() {}

func (x *SaveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type SaveResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 SaveResponse_builder) Build() *SaveResponse {
	m0 := &SaveResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

var File_gophkeeper_proto protoreflect.FileDescriptor

const file_gophkeeper_proto_rawDesc = "" +
	"\n" +
	"\x10gophkeeper.proto\x12\ttransport\"p\n" +
	"\x06Record\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tdata_type\x18\x02 \x01(\tR\bdataType\x12\x1f\n" +
	"\vsecure_data\x18\x03 \x01(\fR\n" +
	"secureData\x12\x14\n" +
	"\x05nonce\x18\x04 \x01(\fR\x05nonce\"&\n" +
	"\x10GetRecordRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x0e\n" +
	"\fSaveResponse2\xcf\x01\n" +
	"\x10TransportService\x128\n" +
	"\n" +
	"SaveRecord\x12\x11.transport.Record\x1a\x17.transport.SaveResponse\x12;\n" +
	"\tGetRecord\x12\x1b.transport.GetRecordRequest\x1a\x11.transport.Record\x12D\n" +
	"\fDeleteRecord\x12\x1b.transport.GetRecordRequest\x1a\x17.transport.SaveResponseB\aZ\x05./;pbb\x06proto3"

var file_gophkeeper_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_gophkeeper_proto_goTypes = []any{
	(*Record)(nil),           // 0: transport.Record
	(*GetRecordRequest)(nil), // 1: transport.GetRecordRequest
	(*SaveResponse)(nil),     // 2: transport.SaveResponse
}
var file_gophkeeper_proto_depIdxs = []int32{
	0, // 0: transport.TransportService.SaveRecord:input_type -> transport.Record
	1, // 1: transport.TransportService.GetRecord:input_type -> transport.GetRecordRequest
	1, // 2: transport.TransportService.DeleteRecord:input_type -> transport.GetRecordRequest
	2, // 3: transport.TransportService.SaveRecord:output_type -> transport.SaveResponse
	0, // 4: transport.TransportService.GetRecord:output_type -> transport.Record
	2, // 5: transport.TransportService.DeleteRecord:output_type -> transport.SaveResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gophkeeper_proto_init() }
func file_gophkeeper_proto_init() {
	if File_gophkeeper_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gophkeeper_proto_rawDesc), len(file_gophkeeper_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gophkeeper_proto_goTypes,
		DependencyIndexes: file_gophkeeper_proto_depIdxs,
		MessageInfos:      file_gophkeeper_proto_msgTypes,
	}.Build()
	File_gophkeeper_proto = out.File
	file_gophkeeper_proto_goTypes = nil
	file_gophkeeper_proto_depIdxs = nil
}
